import { useEffect, useMemo, useRef, useState } from 'react'
import './file-transfer.css'

interface SwitchItem{id:string;name:string;ip:string}
interface RemoteEntry{name:string;path:string;type:'file'|'directory'|'link'|'other';size:number;modifiedAt:number;permissions:number}
interface RemoteListing{path:string;parent:string;entries:RemoteEntry[]}
type Phase='queued'|'local-to-jump'|'jump-to-switch'|'switch-to-jump'|'ready-to-download'|'complete'|'failed'|'cancelled'
interface TransferTask{id:string;direction:'upload'|'download';switchId:string;sourcePath:string;destinationPath:string;fileName:string;totalBytes:number;transferredBytes:number;speedBytesPerSecond:number;phase:Phase;createdAt:number;error?:string;downloadReady?:boolean}
interface LocalItem{name:string;path:string;type:'file'|'directory';file?:File;size:number;modifiedAt:number}
const api=async<T,>(url:string,init?:RequestInit):Promise<T>=>{const response=await fetch(url,{...init,headers:{'content-type':'application/json',...(init?.headers??{})}});const value=await response.json().catch(()=>({error:'request failed'})) as T&{error?:string};if(!response.ok)throw new Error(value.error??'request failed');return value}
const bytes=(value:number):string=>value<1024?value+' B':value<1048576?(value/1024).toFixed(1)+' KB':value<1073741824?(value/1048576).toFixed(1)+' MB':(value/1073741824).toFixed(1)+' GB'
const phaseText:Record<Phase,string>={queued:'等待上传', 'local-to-jump':'本地 → 跳板机','jump-to-switch':'跳板机 → 交换机','switch-to-jump':'交换机 → 跳板机','ready-to-download':'等待保存到本地',complete:'已完成',failed:'失败',cancelled:'已取消'}
const localTree=(files:File[],current:string):LocalItem[]=>{const prefix=current?current+'/':'';const dirs=new Map<string,LocalItem>();const output:LocalItem[]=[];for(const file of files){const full=(file.webkitRelativePath||file.name).replace(/\\/g,'/');if(!full.startsWith(prefix))continue;const rest=full.slice(prefix.length);const slash=rest.indexOf('/');if(slash>=0){const name=rest.slice(0,slash);if(!dirs.has(name))dirs.set(name,{name,path:prefix+name,type:'directory',size:0,modifiedAt:0});continue}output.push({name:rest,path:full,type:'file',file,size:file.size,modifiedAt:file.lastModified})}return[...dirs.values(),...output.sort((a,b)=>a.name.localeCompare(b.name))]}

export function FileTransferView():JSX.Element{
 const [switches,setSwitches]=useState<SwitchItem[]>([]),[switchId,setSwitchId]=useState('sw1')
 const [remote,setRemote]=useState<RemoteListing>({path:'/home/admin',parent:'/home/admin',entries:[]}),[remoteBusy,setRemoteBusy]=useState(false)
 const [localFiles,setLocalFiles]=useState<File[]>([]),[localPath,setLocalPath]=useState(''),[localSelected,setLocalSelected]=useState<Set<string>>(new Set()),[remoteSelected,setRemoteSelected]=useState<Set<string>>(new Set())
 const [transfers,setTransfers]=useState<TransferTask[]>([]),[error,setError]=useState(''),[uploadProgress,setUploadProgress]=useState<Record<string,number>>({})
 const filesRef=useRef<HTMLInputElement>(null),folderRef=useRef<HTMLInputElement>(null)
 const localEntries=useMemo(()=>localTree(localFiles,localPath),[localFiles,localPath])
 const loadRemote=async(path=remote.path,nextSwitch=switchId):Promise<void>=>{setRemoteBusy(true);setError('');try{setRemote(await api<RemoteListing>('/api/files/me/remote?switch='+encodeURIComponent(nextSwitch)+'&path='+encodeURIComponent(path)));setRemoteSelected(new Set())}catch(e){setError(String(e instanceof Error?e.message:e))}finally{setRemoteBusy(false)}}
 const loadTransfers=async():Promise<void>=>{try{const result=await api<{transfers:TransferTask[]}>('/api/files/me/transfers');setTransfers(result.transfers)}catch{}}
 useEffect(()=>{void api<{switches:SwitchItem[]}>('/api/files/me/switches').then((r)=>{setSwitches(r.switches);if(r.switches[0])setSwitchId(r.switches[0].id)}).then(()=>loadRemote('/home/admin','sw1')).catch((e)=>setError(String(e)));void loadTransfers();const timer=setInterval(()=>void loadTransfers(),900);return()=>clearInterval(timer)},[])
 const addFiles=(list:File[]):void=>{setLocalFiles((old)=>{const map=new Map(old.map((f)=>[(f.webkitRelativePath||f.name)+'|'+f.size,f]));for(const file of list)map.set((file.webkitRelativePath||file.name)+'|'+file.size,file);return Array.from(map.values())});setLocalPath('');setLocalSelected(new Set())}
 const uploadOne=async(file:File,relativeName?:string):Promise<void>=>{const fileName=(relativeName??file.name).split('/').at(-1)??file.name;const task=await api<TransferTask>('/api/files/me/transfers',{method:'POST',body:JSON.stringify({direction:'upload',switchId,remoteDirectory:remote.path,fileName,size:file.size,overwrite:false})});await new Promise<void>((resolveUpload,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT','/api/files/me/transfers/'+task.id+'/content');xhr.upload.onprogress=(event)=>{if(event.lengthComputable)setUploadProgress((old)=>({...old,[task.id]:event.loaded/event.total*100}))};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolveUpload():reject(new Error('上传到跳板机失败'));xhr.onerror=()=>reject(new Error('上传连接失败'));xhr.send(file)});void loadTransfers()}
 const uploadSelected=async():Promise<void>=>{setError('');const selected=localEntries.filter((item)=>item.type==='file'&&(localSelected.size===0||localSelected.has(item.path)));if(selected.length===0){setError('请进入包含文件的目录并选择文件');return}try{for(const item of selected)if(item.file)await uploadOne(item.file,item.path)}catch(e){setError(String(e instanceof Error?e.message:e))}}
 const requestDownload=async(entry:RemoteEntry):Promise<void>=>{if(entry.type!=='file')return;await api<TransferTask>('/api/files/me/transfers',{method:'POST',body:JSON.stringify({direction:'download',switchId,remotePath:entry.path})});void loadTransfers()}
 const downloadSelected=async():Promise<void>=>{try{const selected=remote.entries.filter((entry)=>entry.type==='file'&&(remoteSelected.size===0?false:remoteSelected.has(entry.path)));if(!selected.length){setError('请选择需要下载的远程文件');return}for(const entry of selected)await requestDownload(entry)}catch(e){setError(String(e instanceof Error?e.message:e))}}
 const saveReady=(task:TransferTask):void=>{location.href='/api/files/me/transfers/'+task.id+'/download';setTimeout(()=>void loadTransfers(),700)}
 const mkdirRemote=async():Promise<void>=>{const name=window.prompt('在 '+remote.path+' 下新建文件夹：');if(!name)return;try{await api('/api/files/me/remote/directories',{method:'POST',body:JSON.stringify({switchId,parent:remote.path,name})});await loadRemote()}catch(e){setError(String(e instanceof Error?e.message:e))}}
 const selectedSwitch=switches.find((item)=>item.id===switchId)
 return <div className="transfer-root"><header className="transfer-head"><div><small>SECURE FILE BRIDGE</small><strong>本地文件 ⇄ 跳板机 ⇄ 交换机</strong></div><label>目标设备<select value={switchId} onChange={(e)=>{setSwitchId(e.target.value);void loadRemote('/home/admin',e.target.value)}}>{switches.map((sw)=><option key={sw.id} value={sw.id}>{sw.id.toUpperCase()} · {sw.ip}</option>)}</select></label><span className="transfer-connected"><i/>{selectedSwitch?selectedSwitch.name.toUpperCase()+' SFTP':'连接中'}</span></header>
 <main className="transfer-panes"><section className="transfer-pane local" onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();addFiles(Array.from(e.dataTransfer.files))}}><header><div><small>LOCAL / 用户授权目录</small><strong>{localPath||'已选择的本地文件'}</strong></div><div><button disabled={!localPath} onClick={()=>setLocalPath(localPath.split('/').slice(0,-1).join('/'))}>↑</button><button onClick={()=>filesRef.current?.click()}>选择文件</button><button onClick={()=>folderRef.current?.click()}>选择文件夹</button></div></header><input ref={filesRef} hidden multiple type="file" onChange={(e)=>{addFiles(Array.from(e.target.files??[]));e.target.value=''}}/><input ref={folderRef} hidden multiple type="file" {...({webkitdirectory:'',directory:''} as React.InputHTMLAttributes<HTMLInputElement>)} onChange={(e)=>{addFiles(Array.from(e.target.files??[]));e.target.value=''}}/><div className="transfer-path"><span>LOCAL</span><code>{localPath||'选择 Windows 文件，或在系统选择器中输入 \\wsl.localhost\Ubuntu\…'}</code></div><div className="transfer-list"><div className="transfer-columns"><span>Name</span><span>Size</span><span>Modified</span></div>{localEntries.length===0?<div className="transfer-blank"><b>选择本地文件或文件夹</b><p>支持拖放；WSL 文件可通过 Windows 选择器访问 UNC 路径。</p></div>:localEntries.map((item)=><button draggable={item.type==='file'} key={item.path} className={localSelected.has(item.path)?'selected':''} onClick={()=>item.type==='file'&&setLocalSelected((old)=>{const next=new Set(old);next.has(item.path)?next.delete(item.path):next.add(item.path);return next})} onDoubleClick={()=>item.type==='directory'&&setLocalPath(item.path)} onDragStart={(e)=>e.dataTransfer.setData('application/x-local-path',item.path)}><span><i className={item.type}/>{item.name}</span><code>{item.type==='file'?bytes(item.size):'—'}</code><time>{item.modifiedAt?new Date(item.modifiedAt).toLocaleString():'—'}</time></button>)}</div><footer><span>{localFiles.length} 个已授权文件 · {localSelected.size} 个已选择</span><button onClick={()=>void uploadSelected()}>上传到 {switchId.toUpperCase()} →</button></footer></section>
 <div className="transfer-bridge"><span>→</span><i/><small>JUMP<br/>HOST</small><span>←</span></div>
 <section className="transfer-pane remote" onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();const path=e.dataTransfer.getData('application/x-local-path');const item=localEntries.find((x)=>x.path===path);if(item?.file)void uploadOne(item.file,item.path)}}><header><div><small>REMOTE / {switchId.toUpperCase()}</small><strong>{selectedSwitch?.ip??'—'}</strong></div><div><button disabled={remote.parent===remote.path} onClick={()=>void loadRemote(remote.parent)}>↑</button><button onClick={()=>void loadRemote()}>刷新</button><button onClick={()=>void mkdirRemote()}>新建目录</button></div></header><div className="transfer-path"><span>{switchId.toUpperCase()}</span><code>{remote.path}</code></div><div className={'transfer-list '+(remoteBusy?'loading':'')}><div className="transfer-columns"><span>Name</span><span>Size</span><span>Modified</span></div>{remote.entries.map((item)=><button draggable={item.type==='file'} key={item.path} className={remoteSelected.has(item.path)?'selected':''} onClick={()=>item.type==='file'&&setRemoteSelected((old)=>{const next=new Set(old);next.has(item.path)?next.delete(item.path):next.add(item.path);return next})} onDoubleClick={()=>item.type==='directory'?void loadRemote(item.path):void requestDownload(item)}><span><i className={item.type}/>{item.name}</span><code>{item.type==='file'?bytes(item.size):'—'}</code><time>{item.modifiedAt?new Date(item.modifiedAt).toLocaleString():'—'}</time></button>)}</div><footer><span>{remote.entries.length} 项 · {remoteSelected.size} 个已选择</span><button onClick={()=>void downloadSelected()}>← 下载到本地</button></footer></section></main>
 <section className="transfer-queue"><header><div><small>TRANSFER QUEUE</small><strong>传输进度</strong></div><span>{transfers.filter((t)=>!['complete','failed','cancelled'].includes(t.phase)).length} 个活动任务</span></header><div>{transfers.length===0?<p className="queue-empty">暂无传输任务</p>:transfers.slice(0,12).map((task)=>{const percent=task.totalBytes?Math.min(100,task.transferredBytes/task.totalBytes*100):(uploadProgress[task.id]??0);return <article key={task.id} className={task.phase}><span className="direction">{task.direction==='upload'?'↑':'↓'}</span><div className="queue-name"><b>{task.fileName}</b><small>{task.switchId.toUpperCase()} · {phaseText[task.phase]}{task.error?' · '+task.error:''}</small></div><div className="queue-progress"><i style={{width:percent+'%'}}/></div><code>{percent.toFixed(0)}%</code><span className="speed">{task.speedBytesPerSecond?bytes(task.speedBytesPerSecond)+'/s':'—'}</span>{task.phase==='ready-to-download'?<button onClick={()=>saveReady(task)}>保存</button>:!['complete','failed','cancelled'].includes(task.phase)?<button onClick={()=>void api('/api/files/me/transfers/'+task.id+'/cancel',{method:'POST',body:'{}'}).then(loadTransfers)}>×</button>:<em>{task.phase==='complete'?'✓':'!'}</em>}</article>})}</div></section>{error&&<button className="transfer-error" onClick={()=>setError('')}>{error} ×</button>}</div>
}
