import { useEffect, useMemo, useRef, useState } from 'react'
import './agent.css'

type JobStatus = 'created' | 'ready' | 'generating' | 'complete' | 'failed'
interface Message { id:string; role:'user'|'assistant'; content:string; createdAt:number; attachmentIds:string[] }
interface Attachment { id:string; name:string; mimeType:string; size:number; status:'ready'; createdAt:number }
interface Artifact { id:string; name:string; kind:'experiment-yaml'|'switch-config'|'topology-diff'|'package'; size:number; device?:string; createdAt:number }
interface Job { id:string; title:string; status:JobStatus; createdAt:number; updatedAt:number; messages:Message[]; attachments:Attachment[]; artifacts:Artifact[]; summary?:string; error?:string }
interface Provider { provider:'mock'|'deepseek'|'openai-compatible'; baseUrl?:string; model:string; configured:boolean; apiKeyHint?:string }

const jsonFetch = async <T,>(url:string, init?:RequestInit):Promise<T> => { const response=await fetch(url,{...init,headers:{'content-type':'application/json',...(init?.headers??{})}}); const result=await response.json().catch(()=>({error:'请求失败'})) as T & {error?:string}; if(!response.ok) throw new Error(result.error??'请求失败'); return result }
const base64Of = async(file:File):Promise<string> => { const buffer=await file.arrayBuffer(); const bytes=new Uint8Array(buffer); let binary=''; const block=0x8000; for(let i=0;i<bytes.length;i+=block) binary+=String.fromCharCode(...bytes.subarray(i,i+block)); return btoa(binary) }
const formatBytes=(size:number):string => size<1024?size+' B':size<1024*1024?(size/1024).toFixed(1)+' KB':(size/1024/1024).toFixed(1)+' MB'
const statusLabel:Record<JobStatus,string>={created:'新建',ready:'待生成',generating:'生成中',complete:'已完成',failed:'失败'}

export function AgentView():JSX.Element {
  const [jobs,setJobs]=useState<Job[]>([])
  const [activeId,setActiveId]=useState<string>()
  const [provider,setProvider]=useState<Provider>()
  const [providerOpen,setProviderOpen]=useState(false)
  const [providerDraft,setProviderDraft]=useState({provider:'mock',baseUrl:'',model:'sonic-mock-planner',apiKey:''})
  const [input,setInput]=useState('')
  const [busy,setBusy]=useState(false)
  const [dragging,setDragging]=useState(false)
  const [preview,setPreview]=useState<{name:string;text:string}>()
  const [error,setError]=useState('')
  const fileRef=useRef<HTMLInputElement>(null)
  const endRef=useRef<HTMLDivElement>(null)
  const active=jobs.find((job)=>job.id===activeId)
  const switchArtifacts=useMemo(()=>active?.artifacts.filter((item)=>item.kind==='switch-config')??[],[active])

  const refresh=async(selectId?:string):Promise<void>=>{ const result=await jsonFetch<{jobs:Job[]}>('/api/agent/me/jobs'); setJobs(result.jobs); const next=selectId??activeId??result.jobs[0]?.id; if(next!==undefined){setActiveId(next); const job=await jsonFetch<Job>('/api/agent/me/jobs/'+next); setJobs((items)=>items.map((item)=>item.id===job.id?job:item))} }
  useEffect(()=>{ void Promise.all([refresh(),jsonFetch<Provider>('/api/agent/me/provider').then((value)=>{setProvider(value);setProviderDraft({provider:value.provider,baseUrl:value.baseUrl??'',model:value.model,apiKey:''})})]).catch((e)=>setError(String(e))) },[])
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[active?.messages.length])

  const create=async():Promise<Job>=>{ const job=await jsonFetch<Job>('/api/agent/me/jobs',{method:'POST',body:JSON.stringify({title:'新建拓扑任务'})}); setJobs((items)=>[job,...items]);setActiveId(job.id);setPreview(undefined);return job }
  const choose=async(id:string):Promise<void>=>{setActiveId(id);setPreview(undefined);const job=await jsonFetch<Job>('/api/agent/me/jobs/'+id);setJobs((items)=>items.map((item)=>item.id===id?job:item))}
  const upload=async(files:File[]):Promise<void>=>{if(files.length===0)return;setBusy(true);setError('');try{let job=active??await create();for(const file of files){job=await jsonFetch<Job>('/api/agent/me/jobs/'+job.id+'/attachments',{method:'POST',body:JSON.stringify({name:file.name,mimeType:file.type||'text/plain',data:await base64Of(file)})});setJobs((items)=>items.map((item)=>item.id===job.id?job:item))}}catch(e){setError(String(e instanceof Error?e.message:e))}finally{setBusy(false)}}
  const send=async():Promise<void>=>{if(active===undefined||(!input.trim()&&active.attachments.length===0))return;setBusy(true);try{const job=await jsonFetch<Job>('/api/agent/me/jobs/'+active.id+'/messages',{method:'POST',body:JSON.stringify({content:input,attachmentIds:active.attachments.map((item)=>item.id)})});setInput('');setJobs((items)=>items.map((item)=>item.id===job.id?job:item))}catch(e){setError(String(e instanceof Error?e.message:e))}finally{setBusy(false)}}
  const generate=async():Promise<void>=>{if(active===undefined)return;setBusy(true);setError('');setJobs((items)=>items.map((item)=>item.id===active.id?{...item,status:'generating'}:item));try{const job=await jsonFetch<Job>('/api/agent/me/jobs/'+active.id+'/generate',{method:'POST',body:'{}'});setJobs((items)=>items.map((item)=>item.id===job.id?job:item))}catch(e){setError(String(e instanceof Error?e.message:e));await refresh(active.id)}finally{setBusy(false)}}
  const showArtifact=async(artifact:Artifact):Promise<void>=>{if(active===undefined)return;if(artifact.kind==='package'){location.href='/api/agent/me/jobs/'+active.id+'/artifacts/'+artifact.id;return}const response=await fetch('/api/agent/me/jobs/'+active.id+'/artifacts/'+artifact.id);setPreview({name:artifact.name,text:await response.text()})}
  const saveProvider=async():Promise<void>=>{setBusy(true);try{const value=await jsonFetch<Provider>('/api/agent/me/provider',{method:'PUT',body:JSON.stringify(providerDraft)});setProvider(value);setProviderOpen(false)}catch(e){setError(String(e instanceof Error?e.message:e))}finally{setBusy(false)}}

  return <div className="agent-root" onDragEnter={(e)=>{e.preventDefault();setDragging(true)}} onDragOver={(e)=>e.preventDefault()} onDragLeave={(e)=>{if(e.currentTarget===e.target)setDragging(false)}} onDrop={(e)=>{e.preventDefault();setDragging(false);void upload(Array.from(e.dataTransfer.files))}}>
    {dragging&&<div className="agent-drop" role="status" aria-live="polite"><strong>释放以上传到当前 Agent 任务</strong><span>文档、YAML、JSON、拓扑截图</span></div>}
    <aside className="agent-sidebar"><div className="agent-side-head"><div><small>LAB AGENT</small><strong>配置工作台</strong></div><button onClick={()=>void create()}>＋ 新建</button></div><div className="agent-provider"><span className={'dot '+(provider?.configured?'ok':'')} /><div><b>{provider?.provider??'loading'}</b><small>{provider?.model??'正在读取配置'}</small></div><button onClick={()=>setProviderOpen(true)}>设置</button></div><div className="agent-jobs">{jobs.length===0?<p className="agent-empty">还没有任务</p>:jobs.map((job)=><button key={job.id} className={job.id===activeId?'active':''} onClick={()=>void choose(job.id)}><i className={'status '+job.status}/><span><b>{job.title}</b><small>{statusLabel[job.status]} · {new Date(job.updatedAt).toLocaleString()}</small></span></button>)}</div>{active&&<div className="agent-files"><strong>任务附件</strong>{active.attachments.map((file)=><div key={file.id}><span>{file.mimeType.startsWith('image/')?'IMG':'DOC'}</span><p><b>{file.name}</b><small>{formatBytes(file.size)}</small></p></div>)}<button onClick={()=>fileRef.current?.click()}>＋ 添加文件</button></div>}</aside>
    <section className="agent-chat"><header><div><small>AGENT CONVERSATION</small><strong>{active?.title??'请选择或新建任务'}</strong></div>{active&&<button className="agent-generate" disabled={busy||active.attachments.length===0} onClick={()=>void generate()}>{active.status==='generating'?'正在生成…':'生成方案'}</button>}</header><main>{active===undefined?<div className="agent-welcome"><span>◇</span><h2>从实验文档到可执行配置</h2><p>上传文档或粘贴拓扑截图，Agent 将结合实机 LLDP 生成实验拓扑 YAML 和手工配置文件。</p><button onClick={()=>void create()}>创建第一个任务</button></div>:<>{active.messages.map((message)=><article key={message.id} className={'agent-message '+message.role}><div className="avatar">{message.role==='assistant'?'AI':'ME'}</div><div><small>{message.role==='assistant'?'Lab Agent':'你'}</small><p>{message.content}</p></div></article>)}{active.status==='generating'&&<div className="agent-progress" role="status" aria-live="polite"><i/><span>正在采集实机拓扑并生成 YAML / TXT…</span></div>}<div ref={endRef}/></>}</main><footer onPaste={(e)=>{const files=Array.from(e.clipboardData.items).filter((item)=>item.type.startsWith('image/')).map((item)=>item.getAsFile()).filter((file):file is File=>file!==null);if(files.length){e.preventDefault();void upload(files)}}}><input ref={fileRef} hidden multiple type="file" accept=".txt,.md,.json,.yaml,.yml,.pdf,.docx,.xlsx,image/png,image/jpeg,image/webp" onChange={(e)=>{void upload(Array.from(e.target.files??[]));e.target.value=''}}/><textarea disabled={active===undefined||busy} value={input} onChange={(e)=>setInput(e.target.value)} placeholder="描述实验需求，拖入文档，或 Ctrl+V 粘贴拓扑截图…" onKeyDown={(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><div><button onClick={()=>fileRef.current?.click()}>＋ 文件</button><span>Enter 发送 · Shift+Enter 换行</span><button className="send" disabled={active===undefined||busy} onClick={()=>void send()}>发送 →</button></div></footer>{error&&<button type="button" className="agent-error" aria-label="关闭错误提示" onClick={()=>setError('')}>{error} ×</button>}</section>
    <aside className="agent-context"><header><small>JOB CONTEXT</small><strong>上下文与产物</strong></header>{active===undefined?<div className="agent-empty-context">选择任务后查看文件和生成结果</div>:<><div className="agent-stats"><div><b>{active.attachments.length}</b><span>附件</span></div><div><b>{active.artifacts.length}</b><span>产物</span></div><div><b>{switchArtifacts.length}</b><span>设备配置</span></div></div>{active.summary&&<div className="agent-summary"><span>生成摘要</span><p>{active.summary}</p></div>}<div className="agent-artifacts"><strong>生成产物</strong>{active.artifacts.length===0?<p>上传文档并点击“生成方案”</p>:active.artifacts.map((artifact)=><button key={artifact.id} onClick={()=>void showArtifact(artifact)}><span>{artifact.kind==='package'?'ZIP':artifact.name.endsWith('.yml')?'YAML':'TXT'}</span><p><b>{artifact.name}</b><small>{artifact.device??artifact.kind} · {formatBytes(artifact.size)}</small></p><i>{artifact.kind==='package'?'↓':'›'}</i></button>)}</div>{preview&&<div className="agent-preview"><header><b>{preview.name}</b><button onClick={()=>setPreview(undefined)}>×</button></header><pre>{preview.text}</pre></div>}</>}</aside>
    {providerOpen&&<div className="agent-modal" role="dialog" aria-modal="true" aria-label="模型服务配置" onMouseDown={()=>setProviderOpen(false)}><div onMouseDown={(e)=>e.stopPropagation()}><small>AGENT PROVIDER</small><h2>模型服务配置</h2><label>Provider<select value={providerDraft.provider} onChange={(e)=>setProviderDraft({...providerDraft,provider:e.target.value})}><option value="mock">Mock Planner</option><option value="deepseek">DeepSeek</option><option value="openai-compatible">OpenAI Compatible</option></select></label><label>Base URL<input value={providerDraft.baseUrl} onChange={(e)=>setProviderDraft({...providerDraft,baseUrl:e.target.value})} placeholder="https://api.deepseek.com"/></label><label>Model<input value={providerDraft.model} onChange={(e)=>setProviderDraft({...providerDraft,model:e.target.value})}/></label><label>API Key<input type="password" value={providerDraft.apiKey} onChange={(e)=>setProviderDraft({...providerDraft,apiKey:e.target.value})} placeholder={provider?.apiKeyHint??'仅保存在服务端加密存储'}/></label><p>当前版本使用 Mock Planner 跑通生成流程；Provider 接口已经隔离，后续可接入 Pi。</p><div><button onClick={()=>setProviderOpen(false)}>取消</button><button className="primary" onClick={()=>void saveProvider()}>保存</button></div></div></div>}
  </div>
}
