import { randomUUID } from 'node:crypto'
import { createWriteStream } from 'node:fs'
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import type { IncomingMessage } from 'node:http'
import { dirname, join, posix, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { LabConfig } from '../config.ts'
import { withSwitchSftp } from '../collector.ts'

const MODULE_DIR = dirname(fileURLToPath(import.meta.url))
const DATA_ROOT = resolve(process.env.LAB_TRANSFER_DATA_DIR ?? join(MODULE_DIR, '..', 'data', 'transfers'))
const REMOTE_ROOTS = ['/home/admin', '/tmp']
const MAX_FILE_BYTES = 2 * 1024 * 1024 * 1024

export interface RemoteFileEntry { name:string; path:string; type:'file'|'directory'|'link'|'other'; size:number; modifiedAt:number; permissions:number }
export type TransferPhase = 'queued'|'local-to-jump'|'jump-to-switch'|'switch-to-jump'|'ready-to-download'|'complete'|'failed'|'cancelled'
export interface TransferTask { id:string; owner:string; direction:'upload'|'download'; switchId:string; sourcePath:string; destinationPath:string; fileName:string; totalBytes:number; transferredBytes:number; speedBytesPerSecond:number; phase:TransferPhase; createdAt:number; updatedAt:number; error?:string; downloadReady?:boolean; overwrite?:boolean }

const tasks = new Map<string, TransferTask>()
const started = new Map<string, number>()
const safeUserRoot=(username:string):string=>{const root=resolve(DATA_ROOT,'users',username);if(!root.startsWith(resolve(DATA_ROOT,'users')+sep))throw new Error('invalid user');return root}
const taskRoot=(task:TransferTask):string=>join(safeUserRoot(task.owner),task.id)
const safeFileName=(name:string):string=>{const clean=name.replace(/[\/:*?"<>|\r\n\0]/g,'_').trim().slice(0,180);if(!clean||clean==='.'||clean==='..')throw new Error('invalid file name');return clean}
export const safeRemotePath=(value:string):string=>{if(/[\\\0\r\n]/.test(value))throw new Error('invalid remote path');const normalized=posix.normalize(value.startsWith('/')?value:'/'+value);if(!REMOTE_ROOTS.some((root)=>normalized===root||normalized.startsWith(root+'/')))throw new Error('remote path must be under /home/admin or /tmp');return normalized}
const update=(task:TransferTask,patch:Partial<TransferTask>):void=>{Object.assign(task,patch,{updatedAt:Date.now()});tasks.set(task.id,task);void mkdir(taskRoot(task),{recursive:true}).then(()=>writeFile(join(taskRoot(task),'transfer.json'),JSON.stringify(task,null,2),'utf8')).catch(()=>undefined)}
const taskOf=(username:string,id:string):TransferTask=>{const task=tasks.get(id);if(task===undefined||task.owner!==username)throw new Error('transfer not found');return task}
const sftpReaddir=(lab:LabConfig,switchId:string,path:string):Promise<RemoteFileEntry[]>=>withSwitchSftp(lab,switchId,(sftp)=>new Promise((resolveList,reject)=>sftp.readdir(path,(error,list)=>{if(error){reject(error);return}resolveList((list??[]).filter((item)=>item.filename!=='.'&&item.filename!=='..').map((item)=>{const mode=item.attrs.mode??0;const kind:RemoteFileEntry['type']=(mode&0o170000)===0o040000?'directory':(mode&0o170000)===0o120000?'link':(mode&0o170000)===0o100000?'file':'other';return{name:item.filename,path:posix.join(path,item.filename),type:kind,size:item.attrs.size??0,modifiedAt:(item.attrs.mtime??0)*1000,permissions:mode&0o777}}).sort((a,b)=>a.type===b.type?a.name.localeCompare(b.name):a.type==='directory'?-1:1))})))

export async function listRemote(lab:LabConfig,switchId:string,path:string):Promise<{path:string;parent:string;entries:RemoteFileEntry[]}>{const remote=safeRemotePath(path);const entries=await sftpReaddir(lab,switchId,remote);const parent=REMOTE_ROOTS.includes(remote)?remote:safeRemotePath(posix.dirname(remote));return{path:remote,parent,entries}}
export async function makeRemoteDirectory(lab:LabConfig,switchId:string,parent:string,name:string):Promise<void>{const remote=safeRemotePath(posix.join(safeRemotePath(parent),safeFileName(name)));await withSwitchSftp(lab,switchId,(sftp)=>new Promise<void>((resolveMkdir,reject)=>sftp.mkdir(remote,(error)=>error?reject(error):resolveMkdir())))}

export async function createUploadTask(username:string,input:{switchId:string;remoteDirectory:string;fileName:string;size:number;overwrite:boolean}):Promise<TransferTask>{if(!Number.isSafeInteger(input.size)||input.size<0||input.size>MAX_FILE_BYTES)throw new Error('file is too large');const fileName=safeFileName(input.fileName);const destination=safeRemotePath(posix.join(safeRemotePath(input.remoteDirectory),fileName));const now=Date.now();const task:TransferTask={id:'transfer_'+randomUUID(),owner:username,direction:'upload',switchId:input.switchId,sourcePath:fileName,destinationPath:destination,fileName,totalBytes:input.size,transferredBytes:0,speedBytesPerSecond:0,phase:'queued',createdAt:now,updatedAt:now,overwrite:input.overwrite};tasks.set(task.id,task);await mkdir(taskRoot(task),{recursive:true});await writeFile(join(taskRoot(task),'transfer.json'),JSON.stringify(task,null,2),'utf8');return task}

export async function receiveUpload(username:string,id:string,req:IncomingMessage,lab:LabConfig):Promise<TransferTask>{const task=taskOf(username,id);if(task.direction!=='upload'||task.phase!=='queued')throw new Error('transfer cannot accept content');const local=join(taskRoot(task),'staging.bin');started.set(id,Date.now());update(task,{phase:'local-to-jump'});let bytes=0;await new Promise<void>((resolveWrite,reject)=>{const output=createWriteStream(local,{flags:'wx'});req.on('data',(chunk:Buffer)=>{bytes+=chunk.length;if(bytes>MAX_FILE_BYTES){req.destroy(new Error('file too large'));return}const elapsed=Math.max(1,Date.now()-(started.get(id)??Date.now()));update(task,{transferredBytes:bytes,speedBytesPerSecond:Math.round(bytes*1000/elapsed)})});req.on('error',reject);output.on('error',reject);output.on('finish',resolveWrite);req.pipe(output)});if(bytes!==task.totalBytes){update(task,{phase:'failed',error:'received size does not match declared size'});throw new Error(task.error)}update(task,{phase:'jump-to-switch',transferredBytes:0,speedBytesPerSecond:0});void performUpload(task,local,lab);return task}

const performUpload=async(task:TransferTask,local:string,lab:LabConfig):Promise<void>=>{const begin=Date.now();const temporary=task.destinationPath+'.uploading-'+task.id.slice(-8);try{if(!task.overwrite){const exists=await withSwitchSftp(lab,task.switchId,(sftp)=>new Promise<boolean>((resolveStat)=>sftp.stat(task.destinationPath,(error)=>resolveStat(!error))));if(exists)throw new Error('remote file already exists; confirm overwrite to continue')}await withSwitchSftp(lab,task.switchId,(sftp)=>new Promise<void>((resolvePut,reject)=>sftp.fastPut(local,temporary,{step:(transferred)=>{const elapsed=Math.max(1,Date.now()-begin);update(task,{transferredBytes:transferred,speedBytesPerSecond:Math.round(transferred*1000/elapsed)})}},(error)=>error?reject(error):resolvePut())));if(task.phase==='cancelled'){await withSwitchSftp(lab,task.switchId,(sftp)=>new Promise<void>((resolveUnlink)=>sftp.unlink(temporary,()=>resolveUnlink())));return}await withSwitchSftp(lab,task.switchId,(sftp)=>new Promise<void>((resolveRename,reject)=>sftp.rename(temporary,task.destinationPath,(error)=>error?reject(error):resolveRename())));update(task,{phase:'complete',transferredBytes:task.totalBytes,downloadReady:false});await rm(local,{force:true})}catch(error){update(task,{phase:'failed',error:String(error instanceof Error?error.message:error)})}}

export async function createDownloadTask(username:string,input:{switchId:string;remotePath:string} ,lab:LabConfig):Promise<TransferTask>{const remote=safeRemotePath(input.remotePath);const fileName=safeFileName(posix.basename(remote));const now=Date.now();const task:TransferTask={id:'transfer_'+randomUUID(),owner:username,direction:'download',switchId:input.switchId,sourcePath:remote,destinationPath:fileName,fileName,totalBytes:0,transferredBytes:0,speedBytesPerSecond:0,phase:'switch-to-jump',createdAt:now,updatedAt:now};tasks.set(task.id,task);await mkdir(taskRoot(task),{recursive:true});void performDownload(task,lab);return task}
const performDownload=async(task:TransferTask,lab:LabConfig):Promise<void>=>{const local=join(taskRoot(task),'download.bin');const begin=Date.now();try{await withSwitchSftp(lab,task.switchId,(sftp)=>new Promise<void>((resolveGet,reject)=>sftp.fastGet(task.sourcePath,local,{step:(transferred,total)=>{const elapsed=Math.max(1,Date.now()-begin);update(task,{totalBytes:total,transferredBytes:transferred,speedBytesPerSecond:Math.round(transferred*1000/elapsed)})}},(error)=>error?reject(error):resolveGet())));const info=await stat(local);update(task,{phase:'ready-to-download',totalBytes:info.size,transferredBytes:info.size,downloadReady:true})}catch(error){update(task,{phase:'failed',error:String(error instanceof Error?error.message:error)})}}
export const listTransfers=(username:string):TransferTask[]=>Array.from(tasks.values()).filter((task)=>task.owner===username).sort((a,b)=>b.createdAt-a.createdAt).slice(0,100)
export const getTransfer=(username:string,id:string):TransferTask=>taskOf(username,id)
export async function readDownloadedFile(username:string,id:string):Promise<{task:TransferTask;data:Buffer}>{const task=taskOf(username,id);if(task.direction!=='download'||task.phase!=='ready-to-download')throw new Error('download is not ready');const data=await readFile(join(taskRoot(task),'download.bin'));update(task,{phase:'complete'});return{task,data}}
export async function cancelTransfer(username:string,id:string):Promise<TransferTask>{const task=taskOf(username,id);if(task.phase==='complete'||task.phase==='failed')return task;update(task,{phase:'cancelled',error:'cancelled by user'});return task}
