#!/usr/bin/env node
/**
 * Prebuild step: inline the React Flow base stylesheet and our own lab.css
 * into a generated TS module (src/client/styles.gen.ts). The client bundle
 * therefore carries every style as a plain string that a <style> tag injects
 * on mount - no css pipeline needed, no FOUC on first paint.
 * Idempotent; run from the package root via the prebuild hook of pnpm build.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

function readIfExists(path) {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    return undefined
  }
}

const xyflow = readIfExists(join(root, 'node_modules', '@xyflow', 'react', 'dist', 'style.css'))
  ?? readIfExists(join(root, 'node_modules', '@xyflow', 'react', 'dist', 'base.css'))
  ?? ''
const ours = readIfExists(join(root, 'src', 'client', 'lab.css')) ?? ''

const out = [
  '// GENERATED by scripts/inline-css.mjs - do not edit by hand.',
  'export const xyflowCss = ' + JSON.stringify(xyflow),
  'export const labCss = ' + JSON.stringify(ours),
  '',
].join('\n') + '\n'

mkdirSync(join(root, 'src', 'client'), { recursive: true })
writeFileSync(join(root, 'src', 'client', 'styles.gen.ts'), out, 'utf8')
console.log('styles.gen.ts written (xyflow ' + xyflow.length + 'B, lab ' + ours.length + 'B)')