#!/usr/bin/env node
/**
 * Prebuild step: inline the React Flow base stylesheet and our own lab.css
 * into a generated TS module (src/client/styles.gen.ts). The client bundle
 * therefore carries every style as a plain string that a <style> tag injects
 * on mount - no css pipeline needed, no FOUC on first paint.
 * Idempotent; run from the package root via the prebuild hook of pnpm build.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

function readIfExists(path) {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    return undefined
  }
}

const xyflow = readIfExists(join(root, 'node_modules', '@xyflow', 'react', 'dist', 'style.css'))
  ?? readIfExists(join(root, 'node_modules', '@xyflow', 'react', 'dist', 'base.css'))
  ?? ''
const ours = readIfExists(join(root, 'src', 'client', 'lab.css')) ?? ''
// Device-management surfaces (tabs/workspace, file transfer, SSH, xterm).
// The Desktop plugin client never loads lib/client.css, so these ship as a
// runtime-injected string next to lab.css instead of a stylesheet import.
const deviceSources = [
  ['device', readIfExists(join(root, 'src', 'client', 'device-management.css'))],
  ['transfer', readIfExists(join(root, 'src', 'web', 'file-transfer', 'file-transfer.css'))],
  ['ssh', readIfExists(join(root, 'src', 'ssh', 'ssh.css'))],
  ['jenkins', readIfExists(join(root, 'src', 'web', 'jenkins', 'jenkins.css'))],
  ['xterm', readIfExists(join(root, 'node_modules', '@xterm', 'xterm', 'css', 'xterm.css'))],
]
const deviceParts = []
for (const [name, css] of deviceSources) {
  if (css === undefined || css.length === 0) continue
  // ssh.css opens with :root / html,body,#root globals written for the
  // standalone ssh.html page; strip them so the injected copy cannot touch
  // the Desktop shell outside the terminal. Matched by source identity —
  // never by content, because device-management.css also mentions .ssh-page.
  deviceParts.push(name === 'ssh' ? css.slice(Math.max(0, css.indexOf('.ssh-page'))) : css)
}
const device = deviceParts.join('\n')

const out = [
  '// GENERATED by scripts/inline-css.mjs - do not edit by hand.',
  'export const xyflowCss = ' + JSON.stringify(xyflow),
  'export const labCss = ' + JSON.stringify(ours),
  'export const deviceCss = ' + JSON.stringify(device),
  '',
].join('\n') + '\n'

mkdirSync(join(root, 'src', 'client'), { recursive: true })
writeFileSync(join(root, 'src', 'client', 'styles.gen.ts'), out, 'utf8')
console.log('styles.gen.ts written (xyflow ' + xyflow.length + 'B, lab ' + ours.length + 'B, device ' + device.length + 'B)')