/**
 * Injects the bundled styles (React Flow base + our lab.css, both carried
 * as string constants generated by scripts/inline-css.mjs) exactly once per
 * document. Renders nothing.
 */
import { useEffect } from 'react'
import { labCss, xyflowCss } from './styles.gen.ts'

const STYLE_ID = 'dsh-lab-controller-styles'

export function StyleInjector(): null {
	useEffect(() => {
		if (document.getElementById(STYLE_ID) !== null) return
		const element = document.createElement('style')
		element.id = STYLE_ID
		element.textContent = xyflowCss + '\n' + labCss
		document.head.append(element)
	}, [])
	return null
}