/**
 * Injects the bundled styles (React Flow base, lab.css and the device
 * management surfaces, all carried as string constants generated by
 * scripts/inline-css.mjs) exactly once per document. The Desktop plugin
 * client has no stylesheet loader, so runtime injection is the only
 * delivery path there. Renders nothing.
 */
import { useEffect } from 'react'
import { deviceCss, labCss, xyflowCss } from './styles.gen.ts'

const STYLE_ID = 'dsh-lab-controller-styles'

export function StyleInjector(): null {
	useEffect(() => {
		if (document.getElementById(STYLE_ID) !== null) return
		const element = document.createElement('style')
		element.id = STYLE_ID
		element.textContent = xyflowCss + '\n' + labCss + '\n' + deviceCss
		document.head.append(element)
	}, [])
	return null
}